# BISocie.hs
Home: Home

SuccessLogin: You are now logged in.
FailLogin: Fail to login session. Please check your account and password.

HomeOf u@User: #{userFullName u}'s Home
CreateNewProject: Create new project
CrossSearch: Cross search
HumanNetwork: Human Network
Schedule: Schedule

SearchCondition: Search condition

ProjectName: Project name
ParticipantsIdOrName: Participants'Id or Name
IncludeTerminated: Include terminated projects

ProjectList: Project list
Description: Description
CreatedDate: Created date
UpdatedDate: Updated date
Desc: ↑
Asc: ↓

ChangePassword: Change password
YouCannotAccessThisPage: You can't access this page.
