# BISocie.hs
Home: Home

SuccessLogin: You are now logged in.
FailLogin: Fail to login session. Please check your account and password.
InvalidAccount: Your account is invalid.

HomeOf u@User: #{userFullName u}'s Home
CreateNewProject: Create new project
CrossSearch: Cross search
HumanNetwork: Human Network
Schedule: Schedule

SearchCondition: Search condition

ProjectName: Project name
ParticipantsIdOrName: Participants'Id or Name
IncludeTerminated: Include terminated projects

ProjectList: Project list
Description: Description
CreatedDate: Created date
UpdatedDate: Updated date
Desc: ↑
Asc: ↓

ChangePassword: Change password
YouCannotAccessThisPage: You can't access this page.
YouCannotEditThisData: You can't edit this data.
SystemBatch: System batch

ImportStudents: Import students

SendReminder i@Issue: Send reminder mail #{issueSubject i}
Project: Project
Issue: Issue
LimitDate: Limite date
CloseLimitDateOfThisIssue: Close to this issue's limit date
NoteOnThisReminderMail: Don't reply this mail. Please post the url below.
SendingReminder: Sending reminder mails.

ProjectSetting: Project setting
SearchUser: Search user

Required: (Req)
ProjectDescription: Project description
Status: Status
Help: Help
StatusSetting: Status setting
CreateProject: Create new project

Name: Name
EntryYear: Entry year
Teacher: Teacher
Staff: Staff
Admin: Admin
Student: Student
Search: Search

InvalidCommentPosted: Input comment or change any status.
