# BISocie.hs
AccountID: アカウントID
Password: パスワード
Login: ログイン

CurrentPassword: 現在のパスワード
NewPassword: 新しいパスワード
ConfirmPassword: 新しいパスワード(確認)
Update: 変更

Home: ホーム

SuccessLogin: ログインしました.
FailLogin: ログインに失敗しました.アカウントとパスワードを確認してください.

HomeOf u@User: #{userFullName u} ホーム
CreateNewProject: プロジェクト新規作成
CrossSearch: クロスサーチ
HumanNetwork: ヒューマンネットワーク
Schedule: スケジュール

SearchCondition: 検索条件

ProjectName: プロジェクト名
ParticipantsIdOrName: 参加者ID or 氏名
IncludeTerminated: 終了プロジェクトを含む

ProjectList: 参加プロジェクト一覧
Description: 概要
CreatedDate: 作成日
UpdatedDate: 更新日
Desc: ↑
Asc: ↓

ChangePassword: パスワード変更
YouCannotAccessThisPage: あなたはこの情報を閲覧することはできません.
YouCannotEditThisData: あなたはこの情報を編集することはできません.
SystemBatch: システムバッチ

ImportStudents: 学生を登録しました.

SendReminder i@Issue: 【通知メール送信】 #{issueSubject i}
Project: プロジェクト
Issue: タスク
LimitDate: 期限
CloseLimitDateOfThisIssue: このタスクの期限が近づいてきました.
NoteOnThisReminderMail: このメールに直接返信せずにこちらのページから投稿してください.
SendingReminder: 通知メールを送信しました.

ProjectSetting: プロジェクト設定
SearchUser: ユーザ検索

Required: (必須)
ProjectDescription: プロジェクト概要
Status: ステータス
Help: ヘルプ
StatusSetting: ステータス設定
CreateProject: プロジェクトを作成する

Name: 名前
EntryYear: 入学年度
Teacher: 教員
Staff: 職員
Admin: 管理者
Student: 学生
Search: 検索

InvalidCommentPosted: 内容を入力するかタスクの状態を変更してください.
