# BISocie.hs
Home: ホーム

SuccessLogin: ログインしました.
FailLogin: ログインに失敗しました.アカウントとパスワードを確認してください.

HomeOf u@User: #{userFullName u} ホーム
CreateNewProject: プロジェクト新規作成
CrossSearch: クロスサーチ
HumanNetwork: ヒューマンネットワーク
Schedule: スケジュール

SearchCondition: 検索条件

ProjectName: プロジェクト名
ParticipantsIdOrName: 参加者ID or 氏名
IncludeTerminated: 終了プロジェクトを含む

ProjectList: 参加プロジェクト一覧
Description: 概要
CreatedDate: 作成日
UpdatedDate: 更新日
Desc: ↑
Asc: ↓

ChangePassword: パスワード変更
YouCannotAccessThisPage: あなたはこの情報を閲覧することはできません.
