Default: &defaults
  user: cutsea110
  password: cutsea110
  host: localhost
  port: 5432
  database: bisocie
  poolsize: 10

Development:
  database: bisocie_devel
  <<: *defaults

Test:
  database: bisocie_test
  <<: *defaults

Staging:
  database: bisocie_staging
  poolsize: 100
  <<: *defaults

Production:
  database: bisocie
  poolsize: 100
  <<: *defaults
