Default: &defaults
  user: soubun
  password: sougoubunnka
  host: localhost
  port: 5432
  database: bisocie
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: bisocie_test
  <<: *defaults

Staging:
  database: bisocie_staging
  poolsize: 100
  <<: *defaults

Production:
  database: bisocie
  poolsize: 100
  <<: *defaults
