Default: &defaults
  host: "*4" # any IPv4 host
  port: 3001
  approot: "http://localhost:3001"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "https://bisocie.seitoku.ac.jp"
  <<: *defaults
