Default: &defaults
  host: "*4" # any IPv4 host
  port: 3001
  approot: "http://localhost:3001"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  port: 3000
  approot: "http://localhost:3000"
  <<: *defaults

Test:
  <<: *defaults

Staging:
  approot: "https://bisocie2.basement.timedia.co.jp/_bis"
  <<: *defaults

Production:
  #approot: "https://bisocie2.basement.timedia.co.jp/_bis"
  approot: "https://bisocie.seitoku.ac.jp/_bis"
  <<: *defaults
