Default: &defaults
  host: "localhost"
  port: 3001

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "https://bisocie.seitoku.ac.jp"
  <<: *defaults
